# Generated by Django 4.0.1 on 2022-01-25 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_abonne'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='suit'),
        ),
        migrations.DeleteModel(
            name='abonne',
        ),
    ]
